sude: required
language: generic 
services:
  - docker


before_install:
  - docker build -t vickky06/docker-react -f DockerFile.dev .


script:
  - docker run -e CI=true vickky06/docker-react npm run test -- --coverage